- name: Installation et configuration MySQL
  hosts: dbservers
  become: yes

  tasks:

    - name: Installer MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Installer PyMySQL (module Python pour MySQL)
      apt:
        name: python3-pymysql
        state: present

    - name: Démarrer MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Créer base de données
      mysql_db:
        name: population_db
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Créer utilisateur applicatif
      mysql_user:
        name: app_user
        password: "motdepasse123"
        priv: "population_db.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock




